### PR TITLE
Add vagrant 1.7 support

### PR DESCRIPTION
**Pull request by krujos**
PR checks the vagrant version on the machine and if 1.7 or higher uses the new private_key file generated by vagrant instead of the insecure_key that was previously used. I've tested this against our project with both vagrant (with virutalbox provider) 1.7.1 and 1.6.5 and observed correct behavior. 

Extra eyes on the provider logic is probably worthwhile as I'm not sure that vagrant uses the same directory layout for each provider (I confirmed the structure for fusion and virtualbox), nor am I sure if the  :chef_node_name directory always contains only one vm. 

Great tool, thank you for it. 
Josh

### CODE REVIEW

**Comment by krujos** [comment]
Wanted to check on this, any interest in the PR? 
Thanks,
Josh

**Comment by makern** [comment]
Thanks for this. I just merged it manually and did some refactoring.

Can you let me know if master works for you?

**Comment by krujos** [comment]
It works for me. 
Thanks!

**Comment by makern** [comment]
Great. Just released a new version of the gem. Will close this PR.

**Pull request closed without merging**
