### PR TITLE
Fixed issue with OpenStruct class not being found and added a default fo...

### PR DESCRIPTION
**Pull request by mevansam**
Fixed 2 issues in vagrant_server_create.rb. 1) OpenStruct was not found. 2) There was no default value for the distro which was causing a failure when bootstrapping.

### CODE REVIEW

**Comment by makern** [comment]
I have merged the `OpenStruct` and `chef-full` fixes. I think they were issues created by recent versions of chef. Thanks for the fixes.

Can you explain you use case for `inline_config`? Maybe it makes sense to add more explicit options for what you are doing instead of a generic one?

**Comment by mevansam** [comment]
I am using the inline config to add additional configuration to the Vagrant file.You already had some code in place which I hooked into - i.e. the "additions" array in the write_vagrantfile method. I am building a tool that will read a yaml file and construct the knife vagrant command on demand. See here:

https://github.com/mevansam/openstack-ha-cookbook/blob/master/common/vagrant_plugin.yml

**Comment by mevansam** [comment]
I also have another requirement which I am working on which is the ability to pass in vmx params to vmware-fusion similar to vb_customize. I am not sure if you should make explicit options as it will make knife-vagrant more brittle. For example the inline config is being used to pass in additional config for a vagrant plugin but, the knife-vagrant plugin should not be hard-coded to expect that vagrant plugin to be always present.

**Comment by makern** [comment]
Ok, lets untangle this. I can see the benefit of having a `--vmx-customize` option in analog to `--vb-customize`. However this should just be a simple insertion of supplied arguments without any of the special processing you are doing. It is not the place to expand path names to be absolute. If the vmx needs absolute paths (which i doubt) then you should supply them to the `--vmx-customize` options.

If there is a problem with the vmx provider in that it doesn't create disks automatically this is definitely out of place here as well. It might be more appropriate to get this included into vagrant itself.

From looking at https://github.com/mevansam/openstack-ha-cookbook/blob/master/common/vagrant_plugin.yml your use of `--inline-config` is actually against the design goals of this project. You are using it to configure vagrant's build in provisioner(s) whereas knife-vagrant2 is meant to just create a dumb box for knife to bootstrap.

Nevertheless I can see a benefit to having both `--vmx-customize` and `--inline-config` in a way where they simply insert their values into the specific parts of the Vagrant file. Will this be useful to you?

**Comment by mevansam** [comment]
Unlike Virtualbox VMWare does not create disks, as vmx options is a simple config file where as Vagrant maps vb_customize to VBoxManage invocations. VMX options simply modify the vmx file. However, I can work around that. As long as the ability to update the VagrantFile exists it will make it easier to use this plugin for more complex use cases.

The changes you have referenced will work for my use case.  Thanks for making the change.

**Comment by makern** [comment]
Great, I will release a new version of the gem with these changes.

I noticed you made a fork with your own changes. Can I ask you to please change the name, email and homepage in your `knife-vagrant3.gemspec` and `LICENSE` files? I wouldn't want people to accidentally build gems out of your version which have my name and email address in them since I wouldn't be able to help them with any problems.

**Comment by mevansam** [comment]
Will do. I am going to yank that gem within the next couple of weeks once I have moved the vmware disk creation code out.

**Comment by makern** [comment]
Thanks.

**Pull request closed without merging**
